[SETUP]
pause = 30
mqtt_broker = 192.168.120.196
mqtt_port = 1883
mqtt_topic = mpp-solar
mqtt_user = test
mqtt_pass = testerpw

[Inverter_test_1]
port = rfc2217://192.168.120.19:3333
protocol = PI30_v2
baud = 2400
command = QPIGS
outputs = hassd_mqtt

