[SETUP]
pause = 60
mqtt_broker = 192.168.120.196
mqtt_port = 1883
mqtt_user = test
mqtt_pass = testerpw

[INVERTER]
port = rfc2217://192.168.120.19:3333
protocol = PI30_v2
baud = 2400
command = QPIGS
tag = solar
outputs = hassd_mqtt
