name: Build & Push Docker Image

on:
  push:
    branches: [main, beta]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: JamBox-IT/jambox-workflows/.github/workflows/build-docker-image.yml@build-docker-image/v1
    with:
      image_path: 'mppsolar-docker'
      alpine_version: '3.23'
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
