name: Build & Push HA Addon

on:
  push:
    branches: [main, beta]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    uses: JamBox-IT/jambox-workflows/.github/workflows/build-ha-addon.yml@build-ha-addon/v1
    with:
      addon_path: 'ha-mppsolar'
      base_version: '3.23'
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:    ${{ secrets.DOCKERHUB_TOKEN }}
